### ISSUE TITLE
Discord -- Not enough permissions for everything

### ISSUE THREAD

**Issue by yahorbarkouski** [nunchistudio/temporal-land#7]
### What Go version are you running?

1.19.x

### What Temporal Land version are you running?

0.12.x

### Unexpected behavior

Hey guys, can you please open your discord channels on read/write? 🙏 it looks like I can't even read any messages in any channel

**Comment by loicsaintroch** [comment]
Thank you for the feedback. Permissions should be correct now.

**Comment by yahorbarkouski** [comment]
Fixed, thank you!
